# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 21:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50, verbose_name='名称')),
                ('activity_image', models.ImageField(upload_to='shop_image/%Y%m/%d', verbose_name='图片')),
                ('activity_url', models.URLField(verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityArea_name', models.CharField(max_length=50, verbose_name='名称')),
                ('ActivityArea_describe', models.CharField(max_length=255, verbose_name='描述')),
                ('ActivityArea_order', models.IntegerField(default=0, verbose_name='排序')),
                ('ActivityArea_add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('ActivityArea_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('ActivityArea_is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityShop_add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('ActivityShop_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('ActivityShop_ActivityArea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ActivityArea', verbose_name='活动专区id')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=50, verbose_name='名称')),
                ('banner_image', models.ImageField(upload_to='shop_image/%Y%m/%d', verbose_name='图片')),
                ('banner_order', models.IntegerField(default=0, verbose_name='排序')),
                ('banner_add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('banner_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('banner_is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_username', models.CharField(max_length=50, verbose_name='分类名')),
                ('shop_describe', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类介绍')),
                ('shop_add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('shop_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('shop_is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopImage_image', models.ImageField(upload_to='shop_image/%Y%m/%d', verbose_name='商品图片')),
                ('shopImage_add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('shopImage_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('shopImage_is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_trade_name', models.CharField(max_length=20, verbose_name='商品名')),
                ('sku_introduce', models.CharField(max_length=255, verbose_name='简介')),
                ('sku_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='价格')),
                ('sku_stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sku_Sales_volume', models.IntegerField(default=0, verbose_name='销量')),
                ('sku_logo_address', models.ImageField(upload_to='shop_image/%Y%m/%d', verbose_name='logo地址')),
                ('sku_is_upper', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sku_add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('sku_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('sku_is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sku_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Shop', verbose_name='商品分类id')),
            ],
        ),
        migrations.CreateModel(
            name='Spu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_name', models.CharField(max_length=50, verbose_name='名称')),
                ('spu_details', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='详情')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, verbose_name='单位名')),
                ('unit_add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('unit_revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('unit_is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='sku_spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Spu', verbose_name='商品spu_id'),
        ),
        migrations.AddField(
            model_name='sku',
            name='sku_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Unit', verbose_name='单位id'),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='shopImage_Sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Sku', verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Sku', verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='activityshop',
            name='ActivityShop_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Sku', verbose_name='商品id'),
        ),
    ]
