# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '首页活动表', 'verbose_name_plural': '首页活动表'},
        ),
        migrations.AlterModelOptions(
            name='activityarea',
            options={'verbose_name': '活动专区', 'verbose_name_plural': '活动专区'},
        ),
        migrations.AlterModelOptions(
            name='activityshop',
            options={'verbose_name': '专区活动商品', 'verbose_name_plural': '专区活动商品'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页轮播图', 'verbose_name_plural': '首页轮播图'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '分类商品', 'verbose_name_plural': '分类商品'},
        ),
        migrations.AlterModelOptions(
            name='shopimage',
            options={'verbose_name': '商品相册', 'verbose_name_plural': '商品相册'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'verbose_name': '商品sku表', 'verbose_name_plural': '商品sku表'},
        ),
        migrations.AlterModelOptions(
            name='spu',
            options={'verbose_name': '商品spu表', 'verbose_name_plural': '商品spu表'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': '商品单位表', 'verbose_name_plural': '商品单位表'},
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_introduce',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='简介'),
        ),
    ]
