# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=20, null=True)),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3)),
                ('school', models.CharField(max_length=20, null=True)),
                ('home', models.CharField(max_length=20, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('revise_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
