# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20181119_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
