# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_auto_20181120_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default/shop1.png', upload_to='shop/%Y%m/%d', verbose_name='头像LOGO'),
        ),
    ]
