# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='infortx.png', upload_to='shop/%Y%m/%d', verbose_name='头像LOGO'),
        ),
    ]
