# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 15:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_auto_20181121_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gladdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcity', models.CharField(blank=True, max_length=50, null=True, verbose_name='省')),
                ('hproper', models.CharField(blank=True, max_length=50, null=True, verbose_name='市')),
                ('harea', models.CharField(max_length=50, verbose_name='县或区')),
                ('detail', models.CharField(max_length=255, verbose_name='详细地址')),
                ('username', models.CharField(max_length=50, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误!')], verbose_name='联系电话')),
                ('isDefault', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.User', verbose_name='用户id')),
            ],
        ),
    ]
