# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_gladdress'),
    ]

    operations = [
        migrations.AddField(
            model_name='gladdress',
            name='add_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gladdress',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='gladdress',
            name='revise_time',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='gladdress',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='联系电话'),
        ),
    ]
