# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='运输名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='价格')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '运输方式',
                'verbose_name_plural': '运输方式',
                'db_table': 'transport',
            },
        ),
    ]
