# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181125_1033'),
        ('myuser', '0010_auto_20181129_1939'),
        ('allorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, unique=True, verbose_name='订单编号')),
                ('username', models.CharField(max_length=50, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('status', models.SmallIntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待评价'), (3, '取消订单'), (4, '申请退款'), (5, '已完成'), (6, '已评价'), (7, '已退款')], default=0, verbose_name='订单状态')),
                ('transport', models.CharField(max_length=50, verbose_name='运输方式')),
                ('transport_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='运输价格')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品总金额')),
                ('order_money', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实际付款金额')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '订单管理表',
                'verbose_name_plural': '订单管理表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='订单商品的数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='订单商品的价格')),
                ('price_money', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='实际支付的总金额')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Sku', verbose_name='商品skuID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allorder.Order', verbose_name='订单ID')),
            ],
            options={
                'verbose_name': '订单商品管理表',
                'verbose_name_plural': '订单商品管理表',
                'db_table': 'order_Goods',
            },
        ),
        migrations.CreateModel(
            name='Paymethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='支付方式')),
                ('logo', models.ImageField(upload_to='logo/%Y', verbose_name='图片')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('revise_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '支付方式',
                'verbose_name_plural': '支付方式',
                'db_table': 'paymethod',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allorder.Paymethod', verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.User', verbose_name='用户ID'),
        ),
    ]
